/*!
 * \file   meshperfgen.cpp
 * \author Caleb Buahin <caleb.buahin@gmail.com>
 * \date   2026
 * \license GPL-3.0-or-later
 *
 * Mesh Tiled LOD plan (workplans/MESH_TILED_LOD_RENDERING_PLAN_2026-07-13.md)
 * Phase 0 — synthetic terrain-mesh generator for rendering-performance
 * baselines. Emits `[2D_VERTICES]`/`[2D_TRIANGLES]`-format `.2dm` files (the
 * format mesh::InpMeshReader parses) plus a minimal SWMM `.inp` wrapper that
 * references each mesh via `[2D_MESH_FILE]`, so the same fixtures drive both
 * the offscreen test harness and a live GUI session.
 *
 * The analytic surface deliberately carries channels, levees/ridges and a
 * regional slope so the Phase 3 normal-deviation LOD pyramid has real
 * features to preserve; a small high-frequency corrugation gives the thinner
 * removable vertices on the flats.
 *
 * Usage:
 *   mesh_perf_generator [--coupled=N] <output-dir> [triCount ...]
 * Default triangle counts: 500000 1000000 5000000.
 * Output (user-reviewable, per CLAUDE.md Transparent File IO):
 *   <output-dir>/mesh_<N>tri.2dm + mesh_<N>tri.inp
 *
 * `--coupled=N` additionally emits an N-row `[2D_VERTEX_NODE_MAP]` in TAG
 * form, plus the vertex TAG column it resolves against and matching
 * `[JUNCTIONS]` rows in the .inp wrapper. This reproduces the state a GUI
 * SAVE leaves behind (InpMeshWriter PREFERS the tag form), which is the only
 * way to exercise the reader's tag-resolution path — the LOAD_PERF Phase 2
 * fixture. Without it the map section is absent entirely and that path is
 * unreachable.
 */

#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <string>
#include <vector>

namespace {

constexpr double kPi = 3.14159265358979323846;

/*! Analytic terrain (metres). Regional slope + two ridge sets + a meandering
 *  main channel + a straight tributary + fine corrugation. */
double terrainZ(double x, double y, double domainW)
{
    double z = 20.0
             + 0.004 * x                                   // regional slope
             + 3.0 * std::sin(2.0 * kPi * y / 250.0)       // parallel ridges
             + 1.5 * std::sin(2.0 * kPi * (x + y) / 590.0) // diagonal ridges
             + 0.15 * std::sin(x * 1.7) * std::cos(y * 2.3); // fine texture

    // Meandering main channel carved along the x axis.
    const double yc = domainW * 0.5 + 120.0 * std::sin(2.0 * kPi * x / 900.0);
    const double dyc = (y - yc) / 30.0;
    z -= 5.0 * std::exp(-dyc * dyc);

    // Straight tributary channel along y at one third of the domain length.
    const double xc = (x - domainW * (2.0 / 3.0)) / 20.0;  // domainL = 2*domainW
    z -= 3.0 * std::exp(-xc * xc);

    return z;
}

bool generateOne(const std::string &outDir, std::int64_t targetTris,
                 std::int64_t coupledCount)
{
    // 2:1 domain, two triangles per grid cell, 2 m spacing.
    const std::int64_t cells = targetTris / 2;
    std::int64_t cols = static_cast<std::int64_t>(
        std::llround(std::sqrt(static_cast<double>(cells) * 2.0)));
    if (cols < 2) cols = 2;
    std::int64_t rows = (cells + cols - 1) / cols;
    if (rows < 2) rows = 2;
    const double dx = 2.0, dy = 2.0;
    const double domainW = rows * dy;   // width (y)
    const std::int64_t nVerts = (rows + 1) * (cols + 1);
    const std::int64_t nTris  = 2 * rows * cols;

    // Coupled vertices are spread evenly over the mesh, the way real 1D<->2D
    // coupling lands on scattered junctions. Only these carry a TAG: a GUI
    // save tags generated junction vertices, not every vertex, and tagging all
    // of them would inflate the file and change what the baseline measures.
    const std::int64_t nCoupled = (coupledCount > 0)
        ? (coupledCount < nVerts ? coupledCount : nVerts) : 0;
    const std::int64_t coupleStride = (nCoupled > 0) ? (nVerts / nCoupled) : 0;

    const std::string base = outDir + "/mesh_" + std::to_string(targetTris) + "tri";
    const std::string meshPath = base + ".2dm";
    const std::string inpPath  = base + ".inp";

    std::FILE *mf = std::fopen(meshPath.c_str(), "w");
    if (!mf) {
        std::fprintf(stderr, "cannot open %s for writing\n", meshPath.c_str());
        return false;
    }

    std::fprintf(mf, ";; UNITS: SI\n");
    std::fprintf(mf, ";; Synthetic terrain mesh — %lld triangles, %lld vertices\n",
                 static_cast<long long>(nTris), static_cast<long long>(nVerts));
    std::fprintf(mf, ";; Generated by tests/tools/meshperfgen.cpp (Mesh Tiled LOD plan, Phase 0)\n\n");

    std::fprintf(mf, "[2D_VERTICES]\n;;X Y Z%s\n",
                 nCoupled > 0 ? " TAG" : "");
    for (std::int64_t r = 0; r <= rows; ++r) {
        const double y = r * dy;
        for (std::int64_t c = 0; c <= cols; ++c) {
            const double x = c * dx;
            const std::int64_t vi = r * (cols + 1) + c;
            const bool tagged = coupleStride > 0 && (vi % coupleStride) == 0
                                && (vi / coupleStride) < nCoupled;
            if (tagged)
                std::fprintf(mf, "%.2f %.2f %.3f V%lld\n", x, y,
                             terrainZ(x, y, domainW),
                             static_cast<long long>(vi));
            else
                std::fprintf(mf, "%.2f %.2f %.3f\n", x, y, terrainZ(x, y, domainW));
        }
    }

    // MANNINGS_N is required by the [2D_TRIANGLES] parser — rows without it are
    // rejected with "Expected V1 V2 V3 MANNINGS_N [INIT_DEPTH] [TAG]".
    std::fprintf(mf, "\n[2D_TRIANGLES]\n;;V1 V2 V3 MANNINGS_N\n");
    const std::int64_t stride = cols + 1;
    for (std::int64_t r = 0; r < rows; ++r) {
        for (std::int64_t c = 0; c < cols; ++c) {
            const std::int64_t v00 = r * stride + c;
            const std::int64_t v10 = v00 + 1;
            const std::int64_t v01 = v00 + stride;
            const std::int64_t v11 = v01 + 1;
            // CCW in a y-up plane.
            std::fprintf(mf, "%lld %lld %lld 0.035\n",
                         static_cast<long long>(v00), static_cast<long long>(v10),
                         static_cast<long long>(v11));
            std::fprintf(mf, "%lld %lld %lld 0.035\n",
                         static_cast<long long>(v00), static_cast<long long>(v11),
                         static_cast<long long>(v01));
        }
    }
    // [2D_VERTEX_NODE_MAP] in TAG form — the shape InpMeshWriter emits after
    // a save, and the one that used to cost nCoupled x nVertices string
    // compares on re-read (LOAD_PERF Phase 2 / LARGE_MESH_RELOAD F1/F2).
    if (nCoupled > 0) {
        std::fprintf(mf, "\n[2D_VERTEX_NODE_MAP]\n;;VERTEX NODE CD AREA\n");
        for (std::int64_t k = 0; k < nCoupled; ++k) {
            const std::int64_t vi = k * coupleStride;
            std::fprintf(mf, "V%lld J%lld 0.65 2.0\n",
                         static_cast<long long>(vi),
                         static_cast<long long>(k));
        }
    }
    std::fclose(mf);

    // Minimal metric SWMM wrapper so the fixture opens in the live GUI.
    // FLOW_UNITS CMS + ;; UNITS: SI keeps every ft→m conversion out of play.
    std::FILE *inf = std::fopen(inpPath.c_str(), "w");
    if (!inf) {
        std::fprintf(stderr, "cannot open %s for writing\n", inpPath.c_str());
        return false;
    }
    const double domainL = cols * dx;
    const std::string meshFile = "mesh_" + std::to_string(targetTris) + "tri.2dm";
    std::fprintf(inf,
        "[TITLE]\n"
        "Mesh Tiled LOD perf fixture — %lld-triangle synthetic terrain\n"
        "Generated by tests/tools/meshperfgen.cpp\n\n"
        "[OPTIONS]\n"
        "FLOW_UNITS       CMS\n"
        "INFILTRATION     HORTON\n"
        "FLOW_ROUTING     DYNWAVE\n"
        "LINK_OFFSETS     DEPTH\n"
        "MIN_SLOPE        0\n"
        "START_DATE       01/01/2026\n"
        "START_TIME       00:00:00\n"
        "REPORT_START_DATE 01/01/2026\n"
        "REPORT_START_TIME 00:00:00\n"
        "END_DATE         01/01/2026\n"
        "END_TIME         01:00:00\n"
        "REPORT_STEP      00:01:00\n"
        "ROUTING_STEP     00:00:30\n\n"
        "[MAP]\n"
        "DIMENSIONS 0.0 0.0 %.1f %.1f\n"
        "Units      Meters\n\n"
        "[JUNCTIONS]\n"
        ";;Name    Elev    MaxDepth    InitDepth    SurDepth    Aponded\n"
        "J1        10.0    5.0         0            0           0\n\n"
        "[OUTFALLS]\n"
        ";;Name    Elev    Type    StageData    Gated\n"
        "O1        8.0     FREE                 NO\n\n"
        "[CONDUITS]\n"
        ";;Name    From    To    Length    Roughness    InOffset    OutOffset    InitFlow    MaxFlow\n"
        "C1        J1      O1    100.0     0.013        0           0            0           0\n\n"
        "[XSECTIONS]\n"
        ";;Link    Shape       Geom1    Geom2    Geom3    Geom4    Barrels\n"
        "C1        CIRCULAR    1.0      0        0        0        1\n\n"
        "[COORDINATES]\n"
        ";;Node    X-Coord    Y-Coord\n"
        "J1        %.1f       %.1f\n"
        "O1        %.1f       %.1f\n\n"
        "[2D_MESH_FILE]\n"
        "FILE %s\n",
        static_cast<long long>(nTris),
        domainL, domainW,
        domainL * 0.25, domainW * 0.5,
        domainL * 0.25 + 100.0, domainW * 0.5,
        meshFile.c_str());

    // Declare the nodes the coupling map references. Without these the map
    // points at ids that exist nowhere, which the engine rejects — the .2dm
    // would still parse but the fixture would not open end to end.
    if (nCoupled > 0) {
        std::fprintf(inf, "\n[JUNCTIONS]\n"
                          ";;Name  Elev  MaxDepth  InitDepth  SurDepth  Aponded\n");
        for (std::int64_t k = 0; k < nCoupled; ++k)
            std::fprintf(inf, "J%lld  10.0  5.0  0  0  0\n",
                         static_cast<long long>(k));

        std::fprintf(inf, "\n[COORDINATES]\n;;Node  X-Coord  Y-Coord\n");
        for (std::int64_t k = 0; k < nCoupled; ++k) {
            const std::int64_t vi = k * coupleStride;
            const std::int64_t r = vi / (cols + 1);
            const std::int64_t c = vi % (cols + 1);
            std::fprintf(inf, "J%lld  %.2f  %.2f\n",
                         static_cast<long long>(k), c * dx, r * dy);
        }
    }
    std::fclose(inf);

    std::printf("wrote %s (%lld tris, %lld verts, %.0f x %.0f m) + %s\n",
                meshPath.c_str(), static_cast<long long>(nTris),
                static_cast<long long>(nVerts), domainL, domainW,
                inpPath.c_str());
    return true;
}

} // namespace

int main(int argc, char **argv)
{
    std::int64_t coupled = 0;
    std::vector<std::string> positional;
    for (int i = 1; i < argc; ++i) {
        const std::string a = argv[i];
        if (a.rfind("--coupled=", 0) == 0) {
            coupled = std::atoll(a.c_str() + 10);
            continue;
        }
        positional.push_back(a);
    }

    if (positional.empty()) {
        std::fprintf(stderr,
                     "usage: %s [--coupled=N] <output-dir> [triCount ...]\n"
                     "default triCounts: 500000 1000000 5000000\n"
                     "--coupled=N emits an N-row tag-form [2D_VERTEX_NODE_MAP]\n",
                     argv[0]);
        return 2;
    }
    const std::string outDir = positional[0];
    std::vector<std::int64_t> counts;
    for (std::size_t i = 1; i < positional.size(); ++i)
        counts.push_back(std::atoll(positional[i].c_str()));
    if (counts.empty())
        counts = {500000, 1000000, 5000000};

    for (const std::int64_t n : counts)
        if (n < 8 || !generateOne(outDir, n, coupled))
            return 1;
    return 0;
}
